const POSTS_KEY="github-pages-blog-posts-v2",USERS_KEY="github-pages-blog-users-v1",SESSION_KEY="github-pages-blog-session-v1";
const starterPosts=[{id:"welcome",title:"欢迎来到我的博客",author:"博主",content:"这是博客的第一篇文章。\n\n登录后可以发布图文、点赞文章，也可以编辑或删除自己发布的内容。所有数据会保存在当前浏览器中。",createdAt:new Date().toISOString(),views:0,likes:[],photos:[],owner:""}];
const $=s=>document.querySelector(s),views=[$("#list-view"),$("#detail-view"),$("#editor-view")];
let posts=read(POSTS_KEY,starterPosts),users=read(USERS_KEY,[]),currentUser=localStorage.getItem(SESSION_KEY)||"",authMode="login",pendingPhotos=[],sortHot=false;
function read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(){localStorage.setItem(POSTS_KEY,JSON.stringify(posts));localStorage.setItem(USERS_KEY,JSON.stringify(users))}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function date(v){return new Intl.DateTimeFormat("zh-CN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}
function show(v){views.forEach(x=>x.classList.add("hidden"));v.classList.remove("hidden");scrollTo({top:0,behavior:"smooth"})}
function canEdit(p){return !!currentUser&&p.owner===currentUser} function heat(p){return(p.likes?.length||0)*5+(p.views||0)}
function toast(m){let e=$("#toast");e.textContent=m;e.classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add("hidden"),2200)}
function renderAccount(){$("#account-area").innerHTML=currentUser?`<span>你好，${esc(currentUser)}</span><button class="button nav-button" data-action="logout">退出</button>`:`<button class="button nav-button" data-action="open-auth">登录 / 注册</button>`}
function renderList(){let ordered=[...posts].sort((a,b)=>sortHot?heat(b)-heat(a):new Date(b.createdAt)-new Date(a.createdAt));$("#post-count").textContent=`${posts.length} 篇文章`;$("#sort-button").textContent=sortHot?"按时间排序":"按热度排序";$("#post-list").innerHTML=ordered.length?ordered.map(p=>`<article class="post-card">${p.photos?.[0]?`<img class="cover" src="${p.photos[0]}" alt="文章封面">`:""}<div class="post-card-body"><h3>${esc(p.title)}</h3><div class="meta">${esc(p.author)} · ${date(p.createdAt)} · 👁 ${p.views||0} · ❤ ${p.likes?.length||0} · 🔥 ${heat(p)}</div><p class="excerpt">${esc(p.content)}</p><div class="card-footer"><button class="button read-button" data-action="read" data-id="${p.id}">阅读全文 →</button>${canEdit(p)?`<div class="card-actions"><button class="button button-ghost button-small" data-action="edit" data-id="${p.id}">编辑</button><button class="button button-danger button-small" data-action="delete" data-id="${p.id}">删除</button></div>`:""}</div></div></article>`).join(""):`<div class="empty"><h3>还没有文章</h3><p>登录后开始创作。</p></div>`;show($("#list-view"))}
function readPost(id){let p=posts.find(x=>x.id===id);if(!p)return;p.views=(p.views||0)+1;save();let liked=p.likes?.includes(currentUser);$("#detail-view").innerHTML=`<p class="eyebrow dark">ARTICLE</p><h2>${esc(p.title)}</h2><div class="meta">${esc(p.author)} · ${date(p.createdAt)} · 👁 ${p.views} · ❤ ${p.likes?.length||0} · 🔥 ${heat(p)}</div>${p.photos?.length?`<div class="gallery">${p.photos.map((x,i)=>`<img src="${x}" alt="文章照片 ${i+1}">`).join("")}</div>`:""}<div class="detail-content">${esc(p.content)}</div><div class="detail-actions"><button class="button button-ghost" data-action="back">← 返回首页</button><div class="action-group"><button class="button ${liked?"button-liked":"button-primary"}" data-action="like" data-id="${p.id}">${liked?"♥ 已点赞":"♡ 点赞"}</button>${canEdit(p)?`<button class="button button-primary" data-action="edit" data-id="${p.id}">编辑文章</button>`:""}</div></div>`;show($("#detail-view"))}
function requireLogin(cb){currentUser?cb():(openAuth(),toast("请先登录"))}
function openEditor(id=""){let p=posts.find(x=>x.id===id);if(p&&!canEdit(p))return toast("只能编辑自己发布的文章");$("#editor-title").textContent=p?"编辑文章":"写新文章";$("#post-id").value=p?.id||"";$("#title").value=p?.title||"";$("#author").value=p?.author||currentUser;$("#content").value=p?.content||"";pendingPhotos=[...(p?.photos||[])];renderPhotos();show($("#editor-view"));$("#title").focus()}
function renderPhotos(){$("#photo-preview").innerHTML=pendingPhotos.map((x,i)=>`<div><img src="${x}" alt="预览"><button type="button" data-action="remove-photo" data-index="${i}">×</button></div>`).join("")}
function resize(file){return new Promise((ok,no)=>{let r=new FileReader;r.onerror=no;r.onload=()=>{let im=new Image;im.onerror=no;im.onload=()=>{let s=Math.min(1,1400/im.width,1000/im.height),c=document.createElement("canvas");c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext("2d").drawImage(im,0,0,c.width,c.height);ok(c.toDataURL("image/jpeg",.82))};im.src=r.result};r.readAsDataURL(file)})}
function openAuth(mode="login"){authMode=mode;$("#auth-title").textContent=mode==="login"?"登录":"注册";$("#auth-switch").textContent=mode==="login"?"没有账户？立即注册":"已有账户？返回登录";$("#auth-error").textContent="";$("#auth-modal").classList.remove("hidden")}
function closeAuth(){$("#auth-modal").classList.add("hidden");$("#auth-form").reset()}
document.addEventListener("click",e=>{let t=e.target.closest("[data-action]");if(!t)return;let{action,id,index}=t.dataset;if(action==="read")readPost(id);if(action==="edit")requireLogin(()=>openEditor(id));if(action==="delete"&&confirm("确定删除这篇文章吗？")){posts=posts.filter(p=>p.id!==id);save();renderList()}if(action==="back")renderList();if(action==="open-auth")openAuth();if(action==="close-auth")closeAuth();if(action==="logout"){currentUser="";localStorage.removeItem(SESSION_KEY);renderAccount();renderList();toast("已退出登录")}if(action==="remove-photo"){pendingPhotos.splice(+index,1);renderPhotos()}if(action==="like")requireLogin(()=>{let p=posts.find(x=>x.id===id);p.likes||=[];p.likes=p.likes.includes(currentUser)?p.likes.filter(x=>x!==currentUser):[...p.likes,currentUser];save();readPost(id)})});
$("#new-post-button").onclick=()=>requireLogin(()=>openEditor());$("#cancel-button").onclick=renderList;$("#sort-button").onclick=()=>{sortHot=!sortHot;renderList()};$("#auth-switch").onclick=()=>openAuth(authMode==="login"?"register":"login");$("#auth-modal").onclick=e=>{if(e.target===$("#auth-modal"))closeAuth()};
$("#photos").onchange=async e=>{let fs=[...e.target.files];if(pendingPhotos.length+fs.length>6)return toast("每篇文章最多 6 张照片");if(fs.some(f=>f.size>2097152))return toast("单张照片不能超过 2MB");try{pendingPhotos.push(...await Promise.all(fs.map(resize)));renderPhotos()}catch{toast("照片读取失败")}e.target.value=""};
$("#post-form").onsubmit=e=>{e.preventDefault();let id=$("#post-id").value,v={title:$("#title").value.trim(),author:$("#author").value.trim(),content:$("#content").value.trim(),photos:pendingPhotos};if(id)posts=posts.map(p=>p.id===id&&canEdit(p)?{...p,...v}:p);else posts.unshift({id:crypto.randomUUID?.()||`${Date.now()}`,...v,owner:currentUser,createdAt:new Date().toISOString(),views:0,likes:[]});try{save()}catch{return toast("存储空间不足，请减少照片")}e.target.reset();pendingPhotos=[];renderList();toast("文章已保存")};
$("#auth-form").onsubmit=async e=>{e.preventDefault();let name=$("#username").value.trim(),pass=$("#password").value,digest=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(pass)))).map(b=>b.toString(16).padStart(2,"0")).join(""),user=users.find(u=>u.username.toLowerCase()===name.toLowerCase());if(authMode==="register"&&user)return $("#auth-error").textContent="该用户名已存在";if(authMode==="login"&&(!user||user.password!==digest))return $("#auth-error").textContent="用户名或密码不正确";if(authMode==="register"){users.push({username:name,password:digest});save()}currentUser=authMode==="register"?name:user.username;localStorage.setItem(SESSION_KEY,currentUser);closeAuth();renderAccount();renderList();toast(authMode==="register"?"注册成功":"登录成功")};
save();renderAccount();$("#year").textContent=new Date().getFullYear();renderList();
